import { DataMenu } from '../types/types'

export const PriceListMenu: DataMenu[] = [
  { name: 'Nasi Liwet', type: 'food', price: 68 },
  { name: 'Nasi', type: 'food', price: 7 },
  { name: 'Puding', type: 'other', price: 10 },
  { name: 'Salad Buah', type: 'other', price: 15 },
  { name: 'Silky Puding', type: 'other', price: 10 },
  { name: 'Air Mineral', type: 'drink', price: 8 },
  { name: 'Teh Manis Hangat', type: 'drink', price: 15 },
  { name: 'Virgin Mojito Lychee', type: 'drink', price: 32 },
  { name: 'Virgin Mojito Blueberry Lychee', type: 'drink', price: 35 },
  { name: 'Chicken Grilled', type: 'food', price: 68 },
  { name: 'Leci Tea', type: 'drink', price: 25 },
  { name: 'Risol Smoke Beef', type: 'other', price: 24 },
  { name: 'Fuyunghai Chicken', type: 'food', price: 43 },
  { name: 'Lamb Chop', type: 'food', price: 89 },
  { name: 'Pisang Goreng Karamel', type: 'other', price: 20 },
  { name: 'Teh Tawar Panas', type: 'drink', price: 13 },
  { name: 'Nasi Ayam Bakar Madu', type: 'food', price: 41 },
  { name: 'Nasi Ayam Bakar', type: 'food', price: 41 },
  { name: 'Nasi Ayam Goreng Asam Manis', type: 'food', price: 41 },
  { name: 'Nasi Ayam Goreng Lada Hitam', type: 'food', price: 41 },
  { name: 'Nasi Goreng Kepiting', type: 'food', price: 58 },
  { name: 'Tuna Goreng Tepung', type: 'food', price: 49 },
  { name: 'Kerang Bambu Rebus Saus Tiram', type: 'food', price: 56 },
  { name: 'Fuyunghai Seafood', type: 'food', price: 56 },
  { name: 'Koloke Ayam', type: 'food', price: 50 },
  { name: 'Klapertart', type: 'other', price: 12 }
]
